name: app
description: A Data Culture project mobile app for exam preparation
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ui_kit:
    path: packages/ui_kit

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.3
  dio: ^5.6.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  url_launcher: ^6.3.0
  cached_network_image: ^3.4.0
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.1

  path: any
  intl: any
  xml: ^6.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/light/
    - assets/images/dark/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
