name: ui_kit
description: "Data Culture Exam Preparation Mobile application UI Kit."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.1
  google_fonts: ^6.2.0
  intl: ^0.19.0
  mask_text_input_formatter: ^2.9.0
  path: ^1.9.0
  plugin_platform_interface: ^2.0.2

  table_calendar: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - google_fonts/
    - assets/
    - assets/svg/
    - assets/svg/icons/
    - assets/svg/logos/

plugin:
  platforms:
    android:
      package: com.hse.dataculture.ui_kit
      pluginClass: UiKitPlugin
    ios:
      pluginClass: UiKitPlugin
